# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportquestion',
            old_name='time',
            new_name='created_at',
        ),
    ]
