# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171017_1158'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
            preserve_default=False,
        ),
    ]
