# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171222_1103'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportreason',
            unique_together=set([('reason', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('name', 'course')]),
        ),
    ]
