# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_consent_created_at'),
        ('questions', '0002_auto_20171213_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('explanation', models.TextField()),
                ('difficulty', models.FloatField()),
                ('quality', models.FloatField()),
                ('difficultyCount', models.IntegerField()),
                ('qualityCount', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('active_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CourseUser')),
                ('topics', models.ManyToManyField(to='questions.Topic')),
            ],
        ),
    ]
