# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20171222_1103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([]),
        ),
    ]
