# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171222_1103'),
        ('questions', '0003_auto_20171222_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.AddField(
            model_name='topic',
            name='course',
            field=models.ManyToManyField(to='users.Course'),
        ),
    ]
