# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_distractorimage_explanationimage_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionscore',
            name='number_answers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
