# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionscore_number_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
