# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userimage'),
        ('questions', '0005_question_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencymap',
            name='for_competency',
        ),
        migrations.RemoveField(
            model_name='competencymap',
            name='user',
        ),
        migrations.AddField(
            model_name='competency',
            name='topics',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competency',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.CourseUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competencymap',
            name='aggregate_id',
            field=models.IntegerField(null=True),
        ),
    ]
