# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rippleAchievements', '0004_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
