# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-23 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippleAchievements', '0008_auto_20171123_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='view',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
