# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippleAchievements', '0009_auto_20171123_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='url',
            field=models.CharField(default='/<django.db.models.fields.CharField>', max_length=30, unique=True),
        ),
    ]
