# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippleAchievements', '0010_view_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='condition',
            field=models.IntegerField(default=1),
        ),
    ]
