# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rippleAchievements', '0011_achievement_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='icon',
            field=models.CharField(default='Bronze', max_length=30),
        ),
    ]
