# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_created_time'),
        ('users', '0004_userimage'),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CourseUser')),
            ],
        ),
        migrations.CreateModel(
            name='StudyRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='availablerole',
            name='study_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.StudyRole'),
        ),
        migrations.AddField(
            model_name='availablerole',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Topic'),
        ),
    ]
