# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 23:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engagement',
            old_name='item',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='app',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='filter_cond',
        ),
    ]
