# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='consent_images')),
            ],
        ),
        migrations.RenameField(
            model_name='consentform',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='consentimage',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ConsentForm'),
        ),
    ]
