# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171017_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
