# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_consent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuser',
            name='elo_rating',
            field=models.FloatField(default=1000),
        ),
    ]
